#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

import argparse
import platform
import urllib.request

__docformat__ = "restructuredtext en"

url = "http://martin-ueding.de/app/battery-health/submit.php?token={token}&charge={charge:.3f}"

def get_current_charge():
    with open("/sys/class/power_supply/BAT0/charge_now") as f:
        charge_now = int(f.read())
    with open("/sys/class/power_supply/BAT0/charge_full") as f:
        charge_full = int(f.read())

    return charge_now / charge_full * 100

def main():
    options = _parse_args()

    print(get_current_charge())
    query = url.format(token=options.token[0], charge=get_current_charge())
    print(query)
    urllib.request.urlopen(query)

def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("token", metavar="token", type=str, nargs=1, help="Positional arguments.")
    #parser.add_argument("", dest="", type="", default=, help=)
    #parser.add_argument("--version", action="version", version="<the version>")

    return parser.parse_args()


if __name__ == "__main__":
    main()
