#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

import argparse
import matplotlib.pyplot as pl
import numpy as np
import os
import pandas as pd

__docformat__ = "restructuredtext en"

def main():
    options = _parse_args()

    plotopts = {
        "linestyle": "none",
        "marker": ".",
    }

    charge = pd.read_table(
        '/var/lib/upower/history-charge-42T4881-62-1232.dat', index_col=0,
        header=None, names=['timestamp', 'percentage', 'state'])

    rate = pd.read_table(
        '/var/lib/upower/history-rate-42T4881-62-1232.dat', index_col=0,
        header=None, names=['timestamp', 'watt', 'state'])

    charge.plot()
    pl.savefig('upower-charge.pdf')
    pl.clf()

    rate.plot()
    pl.savefig('upower-rate.pdf')
    pl.clf()





def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    #parser.add_argument("args", metavar="N", type=str, nargs="*", help="Positional arguments.")
    #parser.add_argument("", dest="", type="", default=, help=)
    #parser.add_argument("--version", action="version", version="<the version>")

    return parser.parse_args()


if __name__ == "__main__":
    main()
